name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        # Added mkdocs-shadcn here so GitHub knows how to build it
        run: pip install mkdocs mkdocs-shadcn

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-pages --force
